export const BASE_URL = "https://customer-management-production-ab.up.railway.app/"

export const SIGN_UP_IN_FAILURE = 'SIGN_UP_IN_FAILURE'
export const SIGN_IN_UP = 'SIGN_IN_UP'
export const LOGOUT = 'LOGOUT'

export const ADD_PROFIT_SUCESS = "ADD_PROFIT_SUCESS"
export const ADD_PROFIT_FAILED = "ADD_PROFIT_FAILED"
export const ADD_PROFIT_RESET = "ADD_PROFIT_RESET"

export const GET_CREDIT_DEBIT_SUCESS = "GET_CREDIT_DEBIT_SUCESS"
export const GET_CREDIT_DEBIT_FAILED = "GET_CREDIT_DEBIT_FAILED"

export const ACCEPT_REJECT_CREDIT_DEBIT_SUCESS = "ACCEPT_REJECT_CREDIT_DEBIT_SUCESS"
export const ACCEPT_REJECT_CREDIT_DEBIT_FAILED = "ACCEPT_REJECT_CREDIT_DEBIT_FAILED"

export const FECH_CUSTOMER_INFO_SUCESS = 'FECH_CUSTOMER_INFO_SUCESS'
export const FECH_CUSTOMER_INFO_FAILED = 'FECH_CUSTOMER_INFO_FAILED'
export const FECH_CUSTOMER_INFO_REQUEST = 'FECH_CUSTOMER_INFO_REQUEST'
export const RESET_CUSTOMER_REDUX_STATE = 'RESET_CUSTOMER_REDUX_STATE'

export const REMOVE_USER_SUCESS = "REMOVE_USER_SUCESS"
export const REMOVE_USER_FAILED = "REMOVE_USER_FAILED"

export const FORGOT_PASSWORD_REQUEST_FAILED = "FORGOT_PASSWORD_REQUEST_FAILED"
export const FORGOT_PASSWORD_REQUEST_SUCESS = "FORGOT_PASSWORD_REQUEST_SUCESS"

export const RESET_PASSWORD_REQUEST_FAILED = "RESET_PASSWORD_REQUEST_FAILED"
export const RESET_PASSWORD_REQUEST_SUCESS = "RESET_PASSWORD_REQUEST_SUCESS"

export const TRADE_CATEGORY_BALANCE_FAILED = "TRADE_CATEGORY_BALANCE_FAILED" 
export const TRADE_CATEGORY_BALANCE_SUCESS = "TRADE_CATEGORY_BALANCE_SUCESS"

export const FETCH_TRANSACTION_BY_USER_ID_SUCESS = "FETCH_TRANSACTION_BY_USER_ID_SUCESS"
export const FETCH_TRANSACTION_BY_USER_ID_FAILED = "FETCH_TRANSACTION_BY_USER_ID_FAILED"

export const PROFIT_LOSS_SUCESS = "PROFIT_LOSS_SUCESS"
export const PROFIT_LOSS_FAILED = "PROFIT_LOSS_FAILED"

export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const FETCH_NOTIFICATION_FAILURE = "FETCH_NOTIFICATION_FAILURE"
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS"

export const ADD_NOTIFICATION_FAILURE = "ADD_NOTIFICATION_FAILURE"
export const ADD_NOTIFICATION_SUCESS = "ADD_NOTIFICATION_SUCESS"

export const REMOVE_NOTIFICATION_FAILURE = "REMOVE_NOTIFICATION_FAILURE"
export const REMOVE_NOTIFICATION_SUCESS = "REMOVE_NOTIFICATION_SUCESS"

export const FETCH_SHIFT_REQUEST = 'FETCH_SHIFT_REQUEST';
export const FETCH_SHIFT_SUCCESS = 'FETCH_SHIFT_SUCCESS';
export const FETCH_SHIFT_FAILURE = 'FETCH_SHIFT_FAILURE';

export const APPROVE_SHIFT_REQUEST = 'APPROVE_SHIFT_REQUEST';
export const APPROVE_SHIFT_SUCCESS = 'APPROVE_SHIFT_SUCCESS';
export const APPROVE_SHIFT_FAILURE = 'APPROVE_SHIFT_FAILURE';

export const REJECT_SHIFT_REQUEST = 'REJECT_SHIFT_REQUEST';
export const REJECT_SHIFT_SUCCESS = 'REJECT_SHIFT_SUCCESS';
export const REJECT_SHIFT_FAILURE = 'REJECT_SHIFT_FAILURE';

export const FETCH_QUERY_REQUEST = 'FETCH_QUERY_REQUEST';
export const FETCH_QUERY_SUCCESS = 'FETCH_QUERY_SUCCESS';
export const FETCH_QUERY_FAILURE = 'FETCH_QUERY_FAILURE';
export const RESOLVE_QUERY_REQUEST = 'RESOLVE_QUERY_REQUEST';
export const RESOLVE_QUERY_SUCCESS = 'RESOLVE_QUERY_SUCCESS';
export const RESOLVE_QUERY_FAILURE = 'RESOLVE_QUERY_FAILURE';